parameters:

    paypal.api.endpoint: "xxxxxxxx"
    paypal.controller.route.name: "paypal_execute"
    paypal.form.type.class: "Mandrieu\\PaypalBundle\\Form\\Type\\PaypalType"
    paypal.transaction.wrapper.class: "Mandrieu\\PaypalBundle\\Services\\Wrapper\\PaypalTransactionWrapper"
    paypal.manager.class: "Mandrieu\\PaypalBundle\\Services\\PaymillManager"
    paypal.twig.extension.class: "Mandrieu\\PaypalBundle\\Twig\\PaypalExtension"
    paypal.routes.loader.class: "Mandrieu\\PaypalBundle\\Router\\PaypalRoutesLoader"