services:

    paypal.form.type:
        class: %paypal.form.type.class%
        arguments:
            router: @router
            payment.bridge: @payment.bridge
            paypal.controller.route.name: %paypal.controller.route.name%
        tags:
            - { name: form.type, alias: paypal_view }

    paypal.transaction.wrapper:
        class: %paypal.transaction.wrapper.class%

    paypal.manager:
        class: %paypal.manager.class%
        arguments:
            payment.event.dispatcher: @payment.event.dispatcher
            payment.transaction.wrapper: @paypal.transaction.wrapper
            payment.bridge: @payment.bridge

    paypal.twig.extension:
        class: %paypal.twig.extension.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
        tags:
            - { name: twig.extension }

    paypal.routes.loader:
        class: %paypal.routes.loader.class%
        arguments:
            paypal.controller.route.name: %paypal.controller.route.name%
            paypal.controller.route: %paypal.controller.route%
        tags:
            - { name: routing.loader }